import { useEffect, useState } from 'react';
import { ArrowLeft, KeyRound, MonitorSmartphone, Settings2, SlidersHorizontal, Trash2 } from 'lucide-react';
import { api } from '../../services/client';
import type { AdminData, Subject } from '../../types';

type Tab = 'keys' | 'devices' | 'content' | 'settings';
export default function AdminPanel({ onExit, onLogout }: { onExit: () => void; onLogout: () => void }) {
  const [data, setData] = useState<AdminData>(); const [tab, setTab] = useState<Tab>('keys'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [newCode, setNewCode] = useState(''); const [newNote, setNewNote] = useState(''); const [revealedCode, setRevealedCode] = useState('');
  const load = async () => { setBusy(true); setError(''); try { setData(await api.admin()); } catch (e) { setError(e instanceof Error ? e.message : '加载失败'); } finally { setBusy(false); } };
  useEffect(() => { void load(); }, []);
  const act = async (action: string, payload: Record<string, unknown>) => { setBusy(true); setError(''); try { const result = await api.adminAction(action, payload); if (result.code) setRevealedCode(result.code); await load(); } catch (e) { setError(e instanceof Error ? e.message : '操作失败'); setBusy(false); } };
  return <div className="admin-page"><header className="admin-header"><div><button className="icon-text" onClick={onExit}><ArrowLeft size={17} />返回</button><h1>管理后台</h1></div><button className="text-button" onClick={onLogout}>退出登录</button></header>
    <nav className="admin-tabs"><button className={tab === 'keys' ? 'active' : ''} onClick={() => setTab('keys')}><KeyRound size={16} />访问密钥</button><button className={tab === 'devices' ? 'active' : ''} onClick={() => setTab('devices')}><MonitorSmartphone size={16} />设备</button><button className={tab === 'content' ? 'active' : ''} onClick={() => setTab('content')}><SlidersHorizontal size={16} />学科与等级</button><button className={tab === 'settings' ? 'active' : ''} onClick={() => setTab('settings')}><Settings2 size={16} />系统设置</button></nav>
    {error && <p className="banner-error">{error}</p>}{busy && !data && <p className="empty-note">正在加载…</p>}
    {data && <main className="admin-content">
      {tab === 'keys' && <KeysTab data={data} newCode={newCode} newNote={newNote} setNewCode={setNewCode} setNewNote={setNewNote} revealedCode={revealedCode} act={act} />}
      {tab === 'devices' && <section className="admin-section"><h2>设备记录</h2><div className="table-wrap"><table><thead><tr><th>设备</th><th>最近活动</th><th>状态</th><th /></tr></thead><tbody>{data.devices.map((d) => <tr key={d.id}><td className="mono">{d.device_id.slice(0, 16)}…</td><td>{new Date(d.last_seen).toLocaleString()}</td><td>{d.is_banned ? '已停用' : '正常'}</td><td><button className="secondary" onClick={() => void act('device.toggle', { id: d.id, banned: !d.is_banned })}>{d.is_banned ? '恢复' : '停用'}</button></td></tr>)}</tbody></table></div></section>}
      {tab === 'content' && <ContentTab data={data} act={act} />}
      {tab === 'settings' && <SettingsTab data={data} act={act} />}
    </main>}
  </div>;
}

function KeysTab({ data, newCode, newNote, setNewCode, setNewNote, revealedCode, act }: { data: AdminData; newCode: string; newNote: string; setNewCode: (v: string) => void; setNewNote: (v: string) => void; revealedCode: string; act: (a: string, p: Record<string, unknown>) => Promise<void> }) {
  return <><section className="admin-section"><h2>创建访问密钥</h2><form className="inline-form" onSubmit={(e) => { e.preventDefault(); void act('key.create', { code: newCode, note: newNote }); setNewCode(''); setNewNote(''); }}><input value={newCode} onChange={(e) => setNewCode(e.target.value)} placeholder="新的访问密钥" required /><input value={newNote} onChange={(e) => setNewNote(e.target.value)} placeholder="备注" /><button className="primary">创建</button></form>{revealedCode && <p className="one-time-code">密钥只显示一次：<strong>{revealedCode}</strong></p>}</section>
    <section className="admin-section"><h2>密钥与额度</h2><div className="key-grid">{data.keys.map((key) => <article className="key-card" key={key.id}><div><strong className="mono">{key.code_hint}</strong><span>{key.note || '无备注'}</span></div><dl><div><dt>Token</dt><dd>{key.total_tokens} / {key.token_limit ?? '∞'}</dd></div><div><dt>图片</dt><dd>{key.total_images} / {key.image_limit ?? '∞'}</dd></div></dl><div className="card-actions"><button className="secondary" onClick={() => { const value = prompt('Token上限，留空表示无限', key.token_limit?.toString() || ''); void act('key.update', { id: key.id, tokenLimit: value ? Number(value) : null }); }}>Token额度</button><button className="secondary" onClick={() => { const value = prompt('图片上限，留空表示无限', key.image_limit?.toString() || '20'); void act('key.update', { id: key.id, imageLimit: value ? Number(value) : null }); }}>图片额度</button><button className="secondary" onClick={() => void act('key.update', { id: key.id, isActive: !key.is_active })}>{key.is_active ? '停用' : '启用'}</button><button className="danger-icon" onClick={() => confirm('确定删除此密钥及其历史？') && void act('key.delete', { id: key.id })}><Trash2 size={15} /></button></div></article>)}</div></section></>;
}

function ContentTab({ data, act }: { data: AdminData; act: (a: string, p: Record<string, unknown>) => Promise<void> }) {
  const edit = (subject?: Subject) => { const code = subject?.code || prompt('学科编码，例如 physics'); if (!code) return; const label = prompt('显示名称', subject?.label || '') || ''; if (!label) return; const promptPrefix = prompt('学科提示词', subject?.prompt_prefix || '') || ''; void act('subject.upsert', { code, label, promptPrefix, color: subject?.color || 'slate', icon: subject?.icon || 'book', sortOrder: subject?.sort_order || data.subjects.length + 1, isActive: subject?.is_active !== false }); };
  return <div className="admin-two-column"><section className="admin-section"><div className="section-heading"><h2>学科</h2><button className="secondary" onClick={() => edit()}>新增</button></div><div className="simple-list">{data.subjects.map((s) => <div key={s.code}><span><strong>{s.label}</strong><small>{s.code}</small></span><span><button className="secondary" onClick={() => edit(s)}>编辑</button><button className="danger-icon" onClick={() => confirm('删除学科？') && void act('subject.delete', { code: s.code })}><Trash2 size={15} /></button></span></div>)}</div></section>
    <section className="admin-section"><div className="section-heading"><h2>等级</h2><button className="secondary" onClick={() => { const code = prompt('等级编码'); const label = prompt('等级名称'); if (code && label) void act('level.upsert', { code, label, sortOrder: data.levels.length + 1 }); }}>新增</button></div><div className="simple-list">{data.levels.map((l) => <div key={l.code}><span><strong>{l.label}</strong><small>{l.code}</small></span><button className="danger-icon" onClick={() => confirm('删除等级？') && void act('level.delete', { code: l.code })}><Trash2 size={15} /></button></div>)}</div></section></div>;
}

function SettingsTab({ data, act }: { data: AdminData; act: (a: string, p: Record<string, unknown>) => Promise<void> }) {
  const [title, setTitle] = useState(data.config.app_title || 'TongAI'); const [textModel, setTextModel] = useState(data.models.text_model || ''); const [visionModel, setVisionModel] = useState(data.models.vision_model || ''); const [embeddingModel, setEmbeddingModel] = useState(data.models.embedding_model || ''); const [password, setPassword] = useState(''); const [web, setWeb] = useState(data.config.enable_web_search === 'true');
  return <section className="admin-section settings-form"><h2>系统设置</h2><label>网站标题<input value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>文本模型<input value={textModel} onChange={(e) => setTextModel(e.target.value)} /></label><label>视觉模型<input value={visionModel} onChange={(e) => setVisionModel(e.target.value)} /></label><label>Embedding 模型（留空使用全文搜索）<input value={embeddingModel} onChange={(e) => setEmbeddingModel(e.target.value)} /></label><label className="check-row"><input type="checkbox" checked={web} onChange={(e) => setWeb(e.target.checked)} />允许联网搜索</label><label>新管理员密码（至少10位）<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><button className="primary" onClick={() => void act('config.update', { public: { app_title: title, enable_web_search: String(web) }, models: { text_model: textModel, vision_model: visionModel, embedding_model: embeddingModel }, adminPassword: password || undefined })}>保存设置</button><p className="field-note">AI API Key 和 Supabase Service Role 仅从 Vercel 环境变量读取，不会发送到浏览器。</p></section>;
}

